### ISSUE TITLE
Error: Expected fetched plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices"

### ISSUE THREAD

**Issue by snowuyl** [floatinghotpot/cordova-plugin-mmedia#9]
Dear floatinghotpot,
I try to add mmedia plugin. But I encounter the following error.

cordova plugin add https://github.com/floatinghotpot/cordova-plugin-mmedia.git
Fetching plugin "https://github.com/floatinghotpot/cordova-plugin-mmedia.git" via git clone
Installing "com.rjfun.cordova.mmedia" for android
Fetching plugin "com.rjfun.cordova.extension" via plugin registry
npm http GET http://registry.cordova.io/com.rjfun.cordova.extension
npm http 200 http://registry.cordova.io/com.rjfun.cordova.extension
Installing "com.rjfun.cordova.extension" for android
Fetching plugin "https://github.com/floatinghotpot/google-play-services" via git clone
Plugin "https://github.com/floatinghotpot/google-play-services" checked out to git ref "r19".
Failed to install 'com.rjfun.cordova.mmedia':Error: Expected fetched plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:172:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:92:17
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:760:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:574:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)
Error: Expected fetched plugin to have ID "com.google.playservices" but got "cordova-plugin-googleplayservices".
    at checkID (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:172:15)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:92:17
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:760:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:574:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:415:13)

Do you have any advice?

Thanks in advance!

snowuyl

**Comment by floatinghotpot** [comment]
Please try again, or use `cordova plugin add cordova-plugin-mmedia` to load plugin from npm.

**Comment by snowuyl** [comment]
I try to use "cordova plugin add cordova-plugin-mmedia". But Error: 404 Not Found: cordova-plugin-mmedia occur.

Log messages.
cordova plugin add cordova-plugin-mmedia
Fetching plugin "cordova-plugin-mmedia" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-mmedia
npm http 404 http://registry.cordova.io/cordova-plugin-mmedia
Error: 404 Not Found: cordova-plugin-mmedia
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by floatinghotpot** [comment]
your cordova CLI is out of date. please update it to v5.x

**Comment by snowuyl** [comment]
After update cordova to 5.x. It works. Thanks for your great help!
